service: b2w-bot

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLACK_PATH: ${param:SLACK_PATH}

functions:
  b2w:
    handler: handler.b2w
    events:
      - schedule: cron(30 7 ? * 2-6 *)
